---
name: concourse

# replace with `bosh status --uuid`
director_uuid: xxxxx 

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest
- name: cron-resource
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: small 
  stemcell: trusty
  azs: [z1]
  networks:
  - name: dynamic 
    default: [gateway,dns]
  
  - name: floating 
    static_ips:
    - 178.11.11.11 # <-- replace with pre allocated cloudstack public adress
  
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: "https://concourse.mycompany.com/"
      publicly_viewable: true
      # replace with username/password, or configure GitHub auth
      basic_auth_username: atc
      basic_auth_password: wwwwww

      postgresql_database: &atc_db atc
      
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: default
  stemcell: trusty
  persistent_disk_type: large
  azs: [z1]
  networks: [{name: dynamic}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: atc
        password: zzzzzzzzzzzzzz

- name: worker
  instances: 2 
  vm_type: default 
  stemcell: trusty
  azs: [z1]
  networks:
  - name: dynamic 
    default: [gateway,dns]
 

  jobs:
  - name: groundcrew
    release: concourse
    properties: 
      additional_resource_types:
      - type: cron
        image: /var/vcap/packages/cron-resource
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
  - name: install_cron_resource_package
    release: cron-resource
    properties: {}

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
