---
groups:
  - name: cloudstack-stemcell
    jobs:
      - build-cloudstack-xen-ubuntu-trusty

jobs:
  - name: build-cloudstack-xen-ubuntu-trusty
    plan:
      - aggregate:
          - get: bosh-src
          - get: bosh-cpi-src

      - task: create-stemcell
        file: bosh-cpi-src/ci/stemcell/tasks/build.yml
        privileged: true
        params:
          IAAS:                   cloudstack
          HYPERVISOR:             xen
          OS_NAME:                ubuntu
          OS_VERSION:             trusty
          CANDIDATE_BUILD_NUMBER: 3262.4

      - aggregate:
        - put: cloudstack-xen-ubuntu-trusty
          params:
            file: stemcell/bosh-stemcell-*-cloudstack-xen-ubuntu-trusty-go_agent.tgz

        - put: cloudstack-xen-ubuntu-trusty-sha1
          params:
            file: stemcell/bosh-stemcell-*-cloudstack-xen-ubuntu-trusty-go_agent.tgz.sha1

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-release
      branch: master

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: develop
      
      
  - name: candidate-stemcell-ubuntu-trusty
    type: s3
    source:
      regexp: bosh-stemcell-([0-9]+)-cloustack-xen-ubuntu-trusty-go_agent.tgz
      bucket: {{s3_candidate_stemcell_bucket_name}}
      access_key_id: {{aws_builder_access_key}}
      secret_access_key: {{aws_builder_secret_access_key}}
      

  - name: cloudstack-xen-ubuntu-trusty
    type: s3
    source:
      regexp:   bosh-stemcell-([0-9\.]+)-cloudstack-xen-ubuntu-trusty-go_agent.tgz
      bucket: {{s3_candidate_stemcell_bucket_name}}
      access_key_id: {{aws_builder_access_key}}
      secret_access_key: {{aws_builder_secret_access_key}}
      

  - name: cloudstack-xen-ubuntu-trusty-sha1
    type: s3
    source:
      bucket: {{s3_candidate_stemcell_bucket_name}}
      access_key_id: {{aws_builder_access_key}}
      secret_access_key: {{aws_builder_secret_access_key}}
      regexp:   bosh-stemcell-([0-9\.]+)-cloudstack-xen-ubuntu-trusty-go_agent.tgz.sha1
